export const zhCN = {
  app: {
    name: "BayData 控制台",
    shortName: "BayData",
    description: "基于 Next.js 与 Prisma 构建的现代化身份认证系统。",
  },
  auth: {
    response: {
      validationFailed: "请求参数校验失败，请检查输入内容。",
      invalidJson: "请求格式错误，无法解析数据。",
      serverError: "服务器响应异常，请稍后重试。",
      sessionLoaded: "登录状态已同步。",
      unauthenticated: "身份验证已过期，请重新登录。",
      loginSuccess: "登录成功，欢迎回来。",
      logoutSuccess: "已安全退出登录。",
      registerCodeSent: "验证码已发送，请检查您的收件箱。",
      registerSuccess: "注册成功，正在为您准备工作台。",
      resetCodeSent: "重置验证码已发送，请注意查收。",
      resetSuccess: "密码重置成功，请使用新密码登录。",
      networkError: "网络连接不稳定，请检查您的网络设置。",
      emptyResponse: "服务器未返回有效信息，请重试。",
    },
    validation: {
      emailRequired: "请输入电子邮箱地址。",
      emailInvalid: "邮箱格式不正确，请重新输入。",
      passwordRequired: "请输入登录密码。",
      passwordMin: "密码长度不得少于 6 位。",
      codeInvalid: "请输入 6 位数字验证码。",
    },
    error: {
      emailRegistered: "该邮箱已被注册，请尝试直接登录。",
      emailNotRegistered: "该邮箱尚未注册，请先创建账号。",
      passwordMissing: "该账号未设置密码，请通过验证码登录或找回密码。",
      passwordIncorrect: "密码错误，请核对后重试。",
      mailSendFailed: "邮件发送失败，请稍后再试或联系支持。",
      codeMissing: "验证码尚未发送或已失效。",
      codeUnavailable: "验证码无效，请重新获取。",
      codeExpired: "验证码已过期，请重新发送。",
      codeIncorrect: "验证码不正确。",
      requestCodeTooFast: (seconds: number) =>
        `操作过快，请在 ${seconds} 秒后重试。`,
      passwordConfirmMismatch: "两次输入的密码不一致。",
      envMissing: (name: string) => `配置缺失：未找到环境变量 ${name}。`,
    },
    mail: {
      registerSubject: (fromName: string) => `[${fromName}] 注册验证码`,
      registerText: (code: string) =>
        `您好！您的注册验证码为 ${code}，有效期 10 分钟。如非本人操作请忽略。`,
      registerHtml: (code: string) =>
        `<p>您好！</p><p>您的注册验证码是：<strong style="font-size: 1.2em; color: #007bff;">${code}</strong></p><p>该验证码将在 10 分钟后失效，请尽快完成注册。</p>`,
      resetSubject: (fromName: string) => `[${fromName}] 找回密码验证码`,
      resetText: (code: string) =>
        `您正在重置密码，验证码为 ${code}，10 分钟内有效。`,
      resetHtml: (code: string) =>
        `<p>您正在申请重置密码。</p><p>您的验证码是：<strong style="font-size: 1.2em; color: #dc3545;">${code}</strong></p><p>若非本人操作，请及时修改密码以确保账户安全。</p>`,
    },
    ui: {
      badge: "安全认证加密",
      login: {
        title: "登录 BayData",
        subtitle: "访问您的数据控制台",
        emailLabel: "电子邮箱",
        emailPlaceholder: "name@example.com",
        passwordLabel: "密码",
        passwordPlaceholder: "请输入密码",
        forgotPassword: "忘记密码？",
        submit: "立即登录",
        submitting: "正在验证身份...",
        noAccount: "还没有账号？",
        goRegister: "免费注册",
        failureFallback: "登录请求遇到问题，请重试。",
      },
      register: {
        title: "创建账号",
        subtitle: "开启高效的数据分析之旅",
        emailLabel: "电子邮箱",
        emailPlaceholder: "name@example.com",
        sendCode: "获取验证码",
        sendingCode: "发送中...",
        codeLabel: "验证码",
        codePlaceholder: "6 位数字",
        passwordLabel: "设置密码",
        passwordPlaceholder: "建议 8 位以上包含字母数字",
        confirmPasswordLabel: "确认密码",
        confirmPasswordPlaceholder: "请再次输入密码",
        submit: "创建账号",
        submitting: "正在注册...",
        hasAccount: "已有账号？",
        backToLogin: "立即登录",
        needEmailFirst: "请先填写电子邮箱地址。",
        failureFallback: "注册申请提交失败，请重试。",
      },
      forgotPassword: {
        title: "找回密码",
        subtitle: "通过邮箱验证身份并重置密码",
        emailLabel: "注册邮箱",
        emailPlaceholder: "name@example.com",
        sendCode: "获取验证码",
        sendingCode: "发送中...",
        codeLabel: "验证码",
        codePlaceholder: "输入验证码",
        newPasswordLabel: "新密码",
        newPasswordPlaceholder: "设置新密码",
        confirmPasswordLabel: "确认新密码",
        confirmPasswordPlaceholder: "再次输入新密码",
        submit: "确认重置",
        submitting: "正在更新密码...",
        rememberPassword: "我想起密码了",
        backToLogin: "返回登录",
        needEmailFirst: "请先输入您的注册邮箱。",
        failureFallback: "密码重置失败，请联系管理员。",
      },
    },
  },
  dashboard: {
    navTitle: "BayData 控制台",
    welcomeTag: "工作台概述",
    welcomeTitle: "欢迎回来，",
    welcomeDescription:
      "身份认证已成功启用。您现在可以安全地访问受保护的数据资产，管理您的业务卡片、图表及操作流。",
    userId: "账号 ID",
    email: "绑定邮箱",
    verified: "认证状态",
    verifiedYes: "已通过邮箱验证",
    verifiedNo: "待验证邮箱",
    logout: "退出登录",
    loggingOut: "正在安全退出...",
  },
} as const;